import { AiFillStar } from "react-icons/ai";
import {CiCircleRemove} from "react-icons/ci"

const data = [
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR--O9hsrkyCk3aqRkrdxDPtp7oq_zYnf-HVEuiH6czqUEIGpUj",
    title: "Nike Air Monarch IV",
  
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "samsung",
    color: "white",
    category: "Graphiccard",
  },
  {
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSSdV2lA8pMCG5305Jb7kKmtl-5YlcugEP8XxtkCR0OfzbO7pYH",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "apple",
    color: "red",
    category: "watch",
  },

  {
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTBasy2Dn79HB2PbnYhsJzVyeiLdMG3cJpspig3445D3M2rsGzq",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "audionic",
    color: "green",
    category: "sound",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTBbT1ALiXKOba3H790zSLPbYoOs4tnUG9J4CEkFvDx47VVPGae",
    title: "Nike Running Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "apple",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRANoH4FAQnieVJ7tFBbDXvlofq692aWJQYNauLcjJH40xiSgW5",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "apple",
    color: "green",
    category: "laptop",
  },
  {
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQfGXdknDDYg6dGLtw9rRO6pVhpsEhJlRQrT58IwypLHgZNTe_T",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "samsung",
    color: "black",
    category: "phone",
  },

  {
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTdEv28PoJZlvA1pliXXT9cF4v85inSCMMerTJk9AUHZkjqr_4H",
    title: "Loafer Flats",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "lenovo",
    color: "white",
    category: "sound",
  },

  {
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRa0KUROZLGx9Jmre84l8ZXO1Mh2kssyXj--WBMiR33xITCrEa6",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "audionic",
    color: "green",
    category: "sound",
  },

  {
    img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTPvvI765i-2P5E2z14Ra9OhF7jFcPhLqSTPqAFnJHmbIWCewzC",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "audionic",
    color: "blue",
    category: "sneakers",
  },

  {
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQtBrm6kwi52goJePVn4hBE99a9uZqCCPdBQ_UUMmbCUOroQGv6",
    title: "PUMA BLACK-OCE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "250",
    company: "lenovo",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQva-r5JM3NlLe8pA3s1mXvayHOMIbob61eSW4ISPKsPsQttblo",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "250",
    company: "samsung",
    color: "red",
    category: "heels",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSipR5XfMn6OKsIMUO-JUArcOaM_4ueopORJm5C0U1eCOWmeemp",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "250",
    company: "audionic",
    color: "black",
    category: "sound",
  },
  
];

export default data;